obstacle_range: 3.0
raytrace_range: 3.5
footprint: [[-0.7, -0.4], [-0.7, 0.4], [0.7, 0.4], [0.7, -0.4]]
inflation_radius: 1.7
cost_scaling_factor: 4.0
map_type: costmap
observation_sources: scan
scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

