move_base:
  controller_frequency: 5.0
  planner_patience: 10.0
  controller_patience: 10.0
  conservative_reset_dist: 3.0
  oscillation_timeout: 15.0
  oscillation_distance: 0.3
  transform_tolerance: 0.6
  base_local_planner: teb_local_planner/TebLocalPlannerROS
  recovery_behavior_enabled: true
  recovery_behaviors:
    - name: clear_costmap_recovery
      type: "clear_costmap_recovery/ClearCostmapRecovery"

