base_local_planner: teb_local_planner/TebLocalPlannerROS
TebLocalPlannerROS:

  odom_topic: odom
  map_frame: map

  # Robot
  max_vel_x: 1.0   # adjust to your robot
  max_vel_x_backwards: 0.2
  max_vel_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_theta: 2.5
  min_turning_radius: 0.2  # zero for differential drive
  footprint_model:
    type: "polygon"
    vertices: [[-0.7, -0.4], [-0.7, 0.4], [0.7, 0.4], [0.7, -0.4]]

  # Goal tolerance
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  free_goal_vel: false

  # Trajectory
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: false

  # Obstacles
  min_obstacle_dist: 0.5   # IMPORTANT! Half your robot width + safety
  inflation_dist: 1.2
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 0.8

  # Optimization
  no_inner_iterations: 3
  no_outer_iterations: 2
  optimization_activate: true
  optimization_verbose: false

  # Recovery
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 10.0

  # Misc
  exact_arc_length: false
  visualize_hc_graph: false

